#  用SVM做鳶尾花分類

In [1]:
from sklearn import datasets   #引入所需資料集
import pandas as pd            #資料格式整理用
import numpy as np             #運算使用
import matplotlib.pyplot as plt#畫圖用
import seaborn as sns
#評判模型好壞使用
from sklearn.metrics import accuracy_score, confusion_matrix

%matplotlib inline

# 資料引入及處理

In [2]:
#載入iris資料
iris = datasets.load_iris()
#將iris裡的'data'存成DataFrame的形式，此為鳶尾花的4個特徵共150筆
x = pd.DataFrame(iris['data'], columns = iris['feature_names'])
print("target_names: "+ str(iris['target_names']))
#將iris裡的'target'存成DataFrame的形式，此為鳶尾花的分類並以[0,1,2]表示
y = pd.DataFrame(iris['target'], columns=['target'])
#將所需特徵及分類結果整合成一DataFrame
iris_data = pd.concat([x,y], axis=1)

target_names: ['setosa' 'versicolor' 'virginica']


In [3]:
iris_data.info()
#info可用來看資料內的資訊
#此問題為一個多重分類問題，在此我們選用SVM來做處理
x.head(5)#head為pandas裡的函數，此處看x的前5項資料

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
target               150 non-null int32
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

# 資料分割及標準化

In [12]:
#能將資料分成訓練和測試及使用
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
        iris_data[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']], iris_data[['target']], test_size=0.3, random_state=0)

#將資料做標準化(standard  normalization)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print('訓練資料的期望值: ',x_train_std.mean(axis=0),'\n訓練資料的標準差 ',x_train_std.std(axis=0))


訓練資料的期望值:  [-1.24979392e-15 -4.86383420e-17 -1.14194368e-16  3.02403605e-16] 
訓練資料的標準差  [1. 1. 1. 1.]


# 將SVM模型建立並訓練

In [14]:
#引入SVM模型
from sklearn.svm import SVC
#kernel選用linear
svm = SVC(kernel='linear', probability=True)
svm.fit(x_train_std, y_train['target'].values)
#將測試資料套入模型中並看confuse matrix
y_pred = svm.predict(x_test_std)
confu_mat = confusion_matrix(y_test, y_pred, labels=[0,1,2])
accuracy = accuracy_score(y_test, y_pred)
print('accuracy score:', str(accuracy))

print(str(confu_mat))


accuracy score: 0.9777777777777777
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
